---
apiVersion: v1
kind: Template
labels:
  template: "${APP_REPO}-template"
metadata:
  name: "${APP_REPO}-frontend-bc"
  creationTimestamp:
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp:
    labels:
      build: "${APP_REPO}-frontend"
    name: nodejs-8-rhel7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/rhscl/nodejs-8-rhel7:latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhscl/nodejs-8-rhel7:latest
      generation:
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Local
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp:
    labels:
      build: "${APP_REPO}-frontend"
    name: "${APP_REPO}-frontend"
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp:
    labels:
      build: "${APP_REPO}-frontend"
    name: "${APP_REPO}-frontend-${PR_NAME}"
  spec:
    completionDeadlineSeconds: 600
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: "${APP_REPO}-frontend:latest"
    postCommit: {}
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
    runPolicy: SerialLatestOnly
    source:
      contextDir: frontend
      git:
        ref: "${SOURCE_REPO_REF}"
        uri: "${SOURCE_REPO_URL}"
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: '2'
        from:
          kind: ImageStreamTag
          name: nodejs-8-rhel7:latest
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- name: APP_REPO
  description: Application repository name
  required: true
- name: PR_NAME
  description: Pull Request identifier (i.e. pr-5)
  required: true
- name: SOURCE_REPO_REF
  description: Git Pull Request Reference (i.e. pull/CHANGE_ID/head)
  required: true
- name: SOURCE_REPO_URL
  description: Git Repository URL
  required: true
