---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Patroni Postgresql database cluster, with ephemeral storage.
    iconClass: icon-postgresql
    openshift.io/display-name: Patroni Postgresql (Ephemeral)
    openshift.io/long-description: This template deploys a patroni postgresql HA cluster
      with ephemeral storage.
    tags: postgresql
  name: patroni-postgregsql-ephemeral
labels:
  app: "${APP_NAME}-${INSTANCE}"
  app.kubernetes.io/instance: "${INSTANCE}"
  app.kubernetes.io/component: database
  app.kubernetes.io/name: patroni
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: '10'
  cluster-name: "${INSTANCE}"
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: "${NAME}-${INSTANCE}-secret"
  stringData:
    replication-username: "${PATRONI_REPLICATION_USERNAME}"
    replication-password: "${PATRONI_REPLICATION_PASSWORD}"
    superuser-username: "${PATRONI_SUPERUSER_USERNAME}"
    superuser-password: "${PATRONI_SUPERUSER_PASSWORD}"
    app-db-name: "${APP_DB_NAME}"
    app-db-username: "${APP_DB_USERNAME}"
    app-db-password: "${APP_DB_PASSWORD}"
- apiVersion: v1
  kind: Service
  metadata:
    name: "${NAME}-${INSTANCE}"
  spec:
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      cluster-name: "${INSTANCE}"
      role: master
      app.kubernetes.io/name: patroni
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: "${NAME}-${INSTANCE}"
  spec:
    podManagementPolicy: Parallel
    replicas: "${REPLICAS}"
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        statefulset: "${NAME}-${INSTANCE}"
    serviceName: "${NAME}-${INSTANCE}"
    template:
      metadata:
        labels:
          statefulset: "${NAME}-${INSTANCE}"
          cluster-name: "${INSTANCE}"
          app.kubernetes.io/name: patroni
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ${NAME}-${INSTANCE}
              topologyKey: "kubernetes.io/hostname"
        containers:
        - env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: PATRONI_KUBERNETES_LABELS
            value: '{"cluster-name": "${INSTANCE}", "app.kubernetes.io/name": "patroni"}'
          - name: PATRONI_KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: PATRONI_SUPERUSER_USERNAME
            valueFrom:
              secretKeyRef:
                key: superuser-username
                name: "${NAME}-${INSTANCE}-secret"
          - name: PATRONI_SUPERUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: superuser-password
                name: "${NAME}-${INSTANCE}-secret"
          - name: PATRONI_REPLICATION_USERNAME
            valueFrom:
              secretKeyRef:
                key: replication-username
                name: "${NAME}-${INSTANCE}-secret"
          - name: PATRONI_REPLICATION_PASSWORD
            valueFrom:
              secretKeyRef:
                key: replication-password
                name: "${NAME}-${INSTANCE}-secret"
          - name: "PATRONI_${APP_DB_USERNAME}_PASSWORD"
            valueFrom:
              secretKeyRef:
                key: app-db-password
                name: "${NAME}-${INSTANCE}-secret"
          - name: "PATRONI_${APP_DB_USERNAME}_OPTIONS"
            value: "${APP_DB_USER_OPTIONS}"
          - name: PATRONI_LOG_LEVEL
            value: WARNING
          - name: PATRONI_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: PATRONI_POSTGRESQL_DATA_DIR
            value: "/home/postgres/pgdata/pgroot/data"
          - name: PATRONI_POSTGRESQL_PGPASS
            value: "/tmp/pgpass"
          - name: PATRONI_POSTGRESQL_LISTEN
            value: 0.0.0.0:5432
          - name: PATRONI_RESTAPI_LISTEN
            value: 0.0.0.0:8008
          - name: PATRONI_SCOPE
            value: "${INSTANCE}"
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: '500'
          - name: POSTGRESQL_MAX_PREPARED_TRANSACTIONS
            value: '500'
          image: "${IMAGE_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/${IMAGE_STREAM_TAG}"
          imagePullPolicy: Always
          lifecycle:
            # Poststart is required as the wrong folder permissions prevent postgres from starting upon pod restart
            postStart:
              exec:
                command:
                - sh
                - -c
                - '[ -d "/home/postgres/pgdata/pgroot" ] && chmod -R g-rwxs /home/postgres/pgdata/pgroot; exit 0'
          livenessProbe:
            exec:
              command:
              - psql
              - "-w"
              - "-U"
              - postgres
              - "-c"
              - SELECT 1
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          name: postgresql
          ports:
          - containerPort: 8008
            protocol: TCP
          - containerPort: 5432
            protocol: TCP
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          readinessProbe:
            exec:
              command:
              - psql
              - "-w"
              - "-U"
              - postgres
              - "-c"
              - SELECT 1
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          volumeMounts:
          - mountPath: "/home/postgres/pgdata"
            name: postgresql
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccountName: "${NAME}-${INSTANCE}"
        terminationGracePeriodSeconds: 0
        volumes:
        - name: postgresql
          emptyDir: {}
    updateStrategy:
      type: RollingUpdate
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${NAME}-${INSTANCE}"
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: "${NAME}-${INSTANCE}"
  rules:
  - apiGroups:
    - ''
    resources:
    - services
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
    - delete
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
    - delete
  - apiGroups:
    - ''
    resources:
    - endpoints
    verbs:
    - get
    - patch
    - update
    - create
    - list
    - watch
    - delete
  - apiGroups:
    - ''
    resources:
    - pods
    verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: "${NAME}-${INSTANCE}"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: "${NAME}-${INSTANCE}"
  subjects:
  - kind: ServiceAccount
    name: "${NAME}-${INSTANCE}"
parameters:
- name: APP_NAME
  description: Application name
  required: true
- name: NAME
  description: The name of the application for labelling all artifacts.
  displayName: Database Application Name
  required: true
  value: patroni
- name: INSTANCE
  description: The name of this instance of the application
  displayName: Application Instance Name
  required: true
- name: IMAGE_REGISTRY
  description: The base OpenShift docker registry
  displayName: Docker Image Registry
  required: true
  value: docker-registry.default.svc:5000
- name: IMAGE_STREAM_NAMESPACE
  description: The OpenShift Namespace where the patroni and postgresql ImageStream
    resides.
  displayName: ImageStream Namespace
  required: true
  value: openshift
- name: IMAGE_STREAM_TAG
  description: Patroni ImageTag
  displayName: ImageStream Tag
  required: true
  value: patroni:10
- name: MEMORY_LIMIT
  description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  required: true
  value: 512Mi
- name: REPLICAS
  description: The number of database replicas to create.
  displayName: Replica Count
  required: true
  value: "1"
- name: APP_DB_NAME
  description: Name of the application database
  displayName: Application Database Name
  required: true
  value: app
- name: APP_DB_USERNAME
  description: Username of the application database
  displayName: Application Database Username
  required: true
  value: app
- name: APP_DB_PASSWORD
  description: Password of the application database
  displayName: Application Database Password
  generate: expression
  from: "[a-zA-Z0-9]{32}"
- name: APP_DB_USER_OPTIONS
  description: User permission options for the application database
  displayName: Application User Options
  required: true
  value: "createrole,createdb"
- name: PATRONI_SUPERUSER_USERNAME
  description: Username of the superuser account for initialization.
  displayName: Superuser Username
  required: true
  value: postgres
- name: PATRONI_SUPERUSER_PASSWORD
  description: Password of the superuser account for initialization.
  displayName: Superuser Passsword
  generate: expression
  from: "[a-zA-Z0-9]{32}"
  required: true
- name: PATRONI_REPLICATION_USERNAME
  description: Username of the replication account for initialization.
  displayName: Replication Username
  required: true
  value: replication
- name: PATRONI_REPLICATION_PASSWORD
  description: Password of the replication account for initialization.
  displayName: Repication Passsword
  generate: expression
  from: "[a-zA-Z0-9]{32}"
  required: true
