apiVersion: v1
kind: Template
metadata: {}
parameters:
- name: NAME
- name: SUFFIX
- name: VERSION
- name: HOST
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      shared: "true"
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 2
        maxUnavailable: 1
        timeoutSeconds: 180
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}${SUFFIX}
      spec:
        containers:
        - image: " "
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: app-db-name
                  name: ${NAME}-pgsql${SUFFIX}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: app-db-password
                  name: ${NAME}-pgsql${SUFFIX}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: app-db-username
                  name: ${NAME}-pgsql${SUFFIX}
            - name: DB_HOSTNAME
              value: ${NAME}-pgsql-master${SUFFIX}
            - name: SP_ENDPOINT_TEST
              value: spm.gov.bc.ca
            - name: SP_ENDPOINT_PROD
              value: ca-bc-gov-main.collector.snplow.net
          name: app
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 60m
              memory: 64Mi
            limits:
              cpu: 80m
              memory: 96Mi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - app
        from:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: null
    labels: null
    name: ${NAME}${SUFFIX}
  spec:
    maxReplicas: 5
    minReplicas: 2
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: ${NAME}${SUFFIX}
    targetCPUUtilizationPercentage: 85
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    haproxy.router.openshift.io/ip_whitelist: 172.51.0.0/16 142.34.143.128/26 142.22.0.0/16 142.23.0.0/16 142.24.0.0/16 142.25.0.0/16 142.26.0.0/16 142.27.0.0/16 142.28.0.0/16 142.29.0.0/16 142.30.0.0/16 142.31.0.0/16 142.32.0.0/16 142.33.0.0/16 142.34.0.0/16 142.35.0.0/16 142.36.0.0/16
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    host: ${HOST}
    path: ""
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: None
      termination: edge
    to:
      kind: Service
      name: ${NAME}${SUFFIX}
      weight: 100
    wildcardPolicy: None